inherit_from: 
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
  - 'db/**/*'
  - 'bin/*'
  - 'config/environments/*'
  - 'config/application.rb'
  - 'config/initializers/*'
  - 'config/spring.rb'
  - 'lib/tasks/*'
  - 'vendor/**/*'
  - 'path/ruby'

Airbnb/DefaultScope:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Metrics/LineLength:
  Max: 120

