version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - public-data:/app/public
    ports:
      - "3001:3000"
    depends_on:
      - db
      - chrome
  nginx:
    build:      
      context: containers/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/log:/var/log/nginx
      - public-data:/app/public
    depends_on:
      - web
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444

volumes:
  public-data:
  postgresql-data:
    driver: local