version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: database.ymlの再設定
          command: |
            rm ./config/database.yml
            mv ./config/database.ci.yml ./config/database.yml
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 2
      - run:
          name: setup db
          command: docker-compose run web bundle exec rails db:create db:migrate RAILS_ENV=test
      - run:
          name: RSpec
          command: docker-compose run web bin/rspec
      - run:
          name: Rubocop
          command: docker-compose run web bundle exec rubocop
      - run:
          name: docker-compose down
          command: docker-compose down